[versions]
# 定义版本号
fbjni = "0.7.0"
kotlin = "1.9.20"
androidx-annotation = "1.7.0"

[libraries]
fbjni = { module = "com.facebook.fbjni:fbjni", version.ref = "fbjni" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version = "8.13.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }